### ISSUE TITLE
Checkbackend.yml

### ISSUE THREAD

**Issue by pattdepanick** [Workshops-on-Demand/wod-backend#38]
Current deliver script is based on the following check-backend.yml playbook.
Should consider parametizing check-[frontend, api-db-server, backend]

delvier should be able to locate its position to deliver the right playbook.

**Comment by bcornec** [comment]
Fixed in https://github.com/Workshops-on-Demand/wod-backend/commit/dfe412f8ac269f021adbbc14136c829705854460
