### ISSUE TITLE
Jupyterhub / Notebook Login Page and Style Sheet Modification

### ISSUE THREAD

**Issue by pattdepanick** [Workshops-on-Demand/wod-backend#5]
following the steps described in this thread one could customize the login page as well as other pages if willing to 👍  https://professorkazarinoff.github.io/jupyterhub-engr114/login_page/#create-a-templates-directory-and-populate-it-with-jinja-templates

style css:  
/opt/..../share/jupyterhub/static/css
├── style.min.css
└── style.min.css.map

Find a way to inject  modified css to replace default ones
restart jupyterhub service

**Comment by bcornec** [comment]
Now we need to put all that in our install ansible playbooks ;-)
