### ISSUE TITLE
Check presence of SSH keys for install user

### ISSUE THREAD

**Issue by pattdepanick** [Workshops-on-Demand/wod-backend#66]
During install process a set of ssh keys a re by default generated  for the install user.  

1/Check first if install user exists
2/If user exists, check if ssh keys are present
3/if ssh keys are present, keep and reuse them  to prevent reexchanging keys with wod appliances

**Comment by bcornec** [comment]
If using the -k option for build-vagrant or install script, then we force explicitely the receration of the SSH keys.
Otherwise, if key exists it's preserved with other .ssh conf files. If not, then even if the account exists, they are generated.
