### ISSUE TITLE
Notebook deployment issue On Test env

### ISSUE THREAD

**Issue by pattdepanick** [Workshops-on-Demand/wod-backend#79]
the ansiblecopyfolder playbook crashes with the following error : 
TASK [Synchronize target students with Notebooks Workshop content] *********************************************************
fatal: [jupyterhub6.hp.local]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --exclude=*.ipynb --exclude=*.py --exclude=Variables.ps1 --out-format='<<CHANGED>>%i %n%L' /home/wodadmin/wod-notebooks//WKSHP-Python101/ /student/student696//WKSHP-Python101", "msg": "rsync: [Receiver] mkdir \"/student/student696//WKSHP-Python101\" failed: Permission denied (13)\nrsync error: error in file IO (code 11) at main.c(791) [Receiver=3.2.7]\n", "rc": 11}

ansible version on test : ansible core 2.15.4   ubuntu 22.04 where staging is ansible core 2.13.10 ubuntu 20.04

Anisble module issue ?

**Comment by bcornec** [comment]
IIRC we diagnosed it was linked to the ACL not being setup correctly during install or wod-deliver. It seems there is an attribute which has changed with this new version of target system. You should copy the error gathered at install time as this is the one we need to fix.

**Comment by pattdepanick** [comment]
https://superuser.com/questions/1147800/permission-denied-in-ansible-synchronize-module

 synchronize module runs rsync locally on the management machine, not on the target node (for which you set up the privilege escalation). [Module documentation](https://docs.ansible.com/ansible/synchronize_module.html) describes this in details (an excerpt below):

The user and permissions for the synchronize src are those of the user running the Ansible task on the local host (or the remote_user for a delegate_to host when delegate_to is used).

The user and permissions for the synchronize dest are those of the remote_user on the destination host or the become_user if become=yes is active.

So it is accessing your source folder (server:/var/backup/ in the example) as user not root.

If you don't require password for the user to sudo on the target machine (or just do configure it this way for the rsync command) you can use delegate_to: <your_server> parameter combined with rsync_path="sudo rsync" to run it explicitly with sudo.

**Comment by bcornec** [comment]
We do not use the synchronize module as it wasn't able to perform what we want. We had to use the command module, with the rsync command.

**Comment by bcornec** [comment]
And the problem is exhibited with that command, but is coming from another issue, the change of ACL support in the related ansible module.

**Comment by bcornec** [comment]
IT is NOT black magic. We need to solve the issue really :-)
